from django.urls import path

from . import views

app_name = 'projects'

urlpatterns = [
    path('projects/', views.home, name='home'),
    path('projects/<str:key>/', views.project_home, name='project_home'),
    path('projects/<str:key>/backlog/', views.backlog, name='backlog'),
    path('projects/<str:key>/backlog/reorder/', views.backlog_reorder, name='backlog_reorder'),
    path('projects/<str:key>/issues/create-inline/', views.issue_create_inline, name='issue_create_inline'),
    path('projects/<str:key>/epics/create/', views.epic_create, name='epic_create'),
    path('projects/<str:key>/board/', views.board, name='board'),
    path('projects/<str:key>/board/move/', views.board_move, name='board_move'),
    path('projects/<str:key>/columns/', views.board_columns, name='board_columns'),
    path('projects/<str:key>/columns/add/', views.column_add, name='column_add'),
    path('projects/<str:key>/columns/reorder/', views.columns_reorder, name='columns_reorder'),
    path('projects/<str:key>/columns/<int:status_id>/update/', views.column_update, name='column_update'),
    path('projects/<str:key>/columns/<int:status_id>/delete/', views.column_delete, name='column_delete'),
    path('projects/<str:key>/sprints/quick-add/', views.sprint_quick_add, name='sprint_quick_add'),
    path('projects/<str:key>/sprints/', views.sprints, name='sprints'),
    path('projects/<str:key>/archive/', views.archive_list, name='archive'),
    path('projects/<str:key>/sprints/create/', views.sprint_create, name='sprint_create'),
    path('projects/<str:key>/sprints/<int:sprint_id>/capacity/', views.capacity, name='capacity'),
    path('projects/<str:key>/sprints/<int:sprint_id>/capacity/row/', views.capacity_row, name='capacity_row'),
    path('projects/<str:key>/sprints/<int:sprint_id>/capacity/settings/', views.capacity_settings, name='capacity_settings'),
    path('projects/<str:key>/sprints/<int:sprint_id>/retro/', views.retro, name='retro'),
    path('projects/<str:key>/sprints/<int:sprint_id>/retro/add/', views.retro_add, name='retro_add'),
    path('projects/<str:key>/sprints/<int:sprint_id>/retro/<int:item_id>/delete/', views.retro_delete, name='retro_delete'),
    path('projects/<str:key>/sprints/<int:sprint_id>/retro/<int:item_id>/to-issue/', views.retro_to_issue, name='retro_to_issue'),
    path('projects/<str:key>/sprints/move/', views.sprint_move, name='sprint_move'),
    path('projects/<str:key>/sprints/<int:sprint_id>/start/', views.sprint_start, name='sprint_start'),
    path('projects/<str:key>/sprints/<int:sprint_id>/complete/', views.sprint_complete, name='sprint_complete'),
    path('projects/<str:key>/timeline/', views.timeline, name='timeline'),
    path('browse/<str:issue_key>/', views.issue_browse, name='browse'),
    path('browse/<str:issue_key>/panel/', views.issue_panel, name='issue_panel'),
    path('browse/<str:issue_key>/field/<str:field>/', views.issue_field, name='issue_field'),
    path('browse/<str:issue_key>/comments/', views.comment_add, name='comment_add'),
    path('browse/<str:issue_key>/comments/<int:comment_id>/delete/', views.comment_delete, name='comment_delete'),
    path('browse/<str:issue_key>/ac/', views.ac_add, name='ac_add'),
    path('browse/<str:issue_key>/ac/<int:ac_id>/toggle/', views.ac_toggle, name='ac_toggle'),
    path('browse/<str:issue_key>/ac/<int:ac_id>/delete/', views.ac_delete, name='ac_delete'),
    path('browse/<str:issue_key>/subtasks/', views.subtask_add, name='subtask_add'),
    path('browse/<str:issue_key>/activity/', views.issue_activity, name='issue_activity'),
    path('browse/<str:issue_key>/archive/', views.issue_archive, name='issue_archive'),
    path('browse/<str:issue_key>/delete/', views.issue_delete, name='issue_delete'),
    path('browse/<str:issue_key>/links/search/', views.link_search, name='link_search'),
    path('browse/<str:issue_key>/links/add/', views.link_add, name='link_add'),
    path('browse/<str:issue_key>/links/<int:page_id>/remove/', views.link_remove, name='link_remove'),
]
