# Generated by Django 6.0.6 on 2026-06-11 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='page',
            name='view_role',
            field=models.CharField(choices=[('viewer', 'Everyone in the space'), ('member', 'Members and admins'), ('admin', 'Admins only')], default='viewer', max_length=10),
        ),
    ]
