# Generated by Django 6.0.6 on 2026-06-12 06:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('wiki', '0002_page_is_published_page_view_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='issue',
            name='linked_pages',
            field=models.ManyToManyField(blank=True, related_name='linked_issues', to='wiki.page'),
        ),
        migrations.AddField(
            model_name='sprint',
            name='public_holidays',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='RetroItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('went_well', 'What went well'), ('improve', 'What could improve'), ('action', 'Action items')], max_length=12)),
                ('text', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retro_items', to=settings.AUTH_USER_MODEL)),
                ('linked_issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retro_items', to='projects.issue')),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retro_items', to='projects.sprint')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SprintCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_points', models.PositiveSmallIntegerField(default=10, help_text='Story points this person can take in a full sprint.')),
                ('leave_days', models.PositiveSmallIntegerField(default=0)),
                ('role', models.CharField(choices=[('none', '—'), ('team_lead', 'Team lead'), ('tech_lead', 'Tech lead')], default='none', max_length=10)),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacities', to='projects.sprint')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprint_capacities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'sprint capacities',
                'unique_together': {('sprint', 'user')},
            },
        ),
    ]
