# Generated by Django 6.0.6 on 2026-06-11 10:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('key', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z][A-Z0-9]{1,9}$', 'Keys are 2–10 characters, uppercase letters/digits, starting with a letter (e.g. CLIC).')])),
                ('space_type', models.CharField(choices=[('software', 'Jira project'), ('wiki', 'Confluence space')], max_length=10)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#0052CC', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issue_counter', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_spaces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SpaceMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('member', 'Member'), ('viewer', 'Viewer')], default='member', max_length=10)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.space')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='space_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['space', 'user__first_name'],
                'unique_together': {('space', 'user')},
            },
        ),
        migrations.AddField(
            model_name='space',
            name='members',
            field=models.ManyToManyField(related_name='spaces', through='core.SpaceMembership', to=settings.AUTH_USER_MODEL),
        ),
    ]
