# Generated by Django 6.0.6 on 2026-06-11 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='space_type',
            field=models.CharField(choices=[('software', 'Atlas project'), ('wiki', 'Hub space')], max_length=10),
        ),
    ]
