# Generated by Django 6.0.6 on 2026-06-12 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_space_space_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='linked_hub_space',
            field=models.ForeignKey(blank=True, limit_choices_to={'space_type': 'wiki'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_projects', to='core.space'),
        ),
    ]
