# Generated by Django 6.0.6 on 2026-06-11 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=30)),
                ('message', models.TextField()),
                ('message_type', models.CharField(choices=[('MANUAL', 'Manual'), ('ISSUE_ASSIGNED', 'Issue assigned'), ('MENTION', '@Mention'), ('SPRINT_STARTED', 'Sprint started'), ('SPRINT_COMPLETED', 'Sprint completed'), ('PASSWORD_RESET', 'Password reset')], default='MANUAL', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppDevice',
            fields=[
            ],
            options={
                'verbose_name': 'Connection',
                'verbose_name_plural': 'Connection',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('whatsapp.whatsappmessage',),
        ),
    ]
